ParadiseZ = ParadiseZ or {}
-----------------------            ---------------------------
ParadiseZ.ZoneData = {
    ["Raven Creek"] = {
        name = "Raven Creek", 
        x1 = 2400,
        y1 = 11100, 
        x2 = 5099,
        y2 = 14999,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Louisville"] = {
        name = "Louisville", 
        x1 = 12000, 
        y1 = 900, 
        x2 = 14999,
        y2 = 3899,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["West Point"] = {
        name = "West Point", 
        x1 = 11100, 
        y1 = 6580, 
        x2 = 13199,
        y2 = 7499,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["MarchRidge"] = {
        name = "MarchRidge", 
        x1 = 9600, 
        y1 = 12600, 
        x2 = 10499,
        y2 = 13199,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Muldraugh"] = {
        name = "Muldraugh", 
        x1 = 10490, 
        y1 = 9160, 
        x2 = 11000,
        y2 = 10700,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Rosewood"] = {
        name = "Rosewood", 
        x1 = 7800, 
        y1 = 10800, 
        x2 = 8699,
        y2 = 12299,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Riverside"] = {
        name = "Riverside", 
        x1 = 5400, 
        y1 = 5100, 
        x2 = 6899,
        y2 = 5699,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Bedford Falls"] = {
        name = "Bedford Falls", 
        x1 = 12600, 
        y1 = 7500, 
        x2 = 14400,
        y2 = 13200,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Fort Redstone"] = {
        name = "Fort Redstone", 
        x1 = 5400, 
        y1 = 11100, 
        x2 = 5999,
        y2 = 12299,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Lake Ivy Township"] = {
        name = "Lake Ivy Township", 
        x1 = 8700, 
        y1 = 9600, 
        x2 = 9599,
        y2 = 10499,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Greenport"] = {
        name = "Greenport", 
        x1 = 8100, 
        y1 = 7400, 
        x2 = 8699,
        y2 = 7799,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Shipping Port"] = {
        name = "Shipping Port", 
        x1 = 12289, 
        y1 = 3502, 
        x2 = 12600,
        y2 = 5000,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Homepie"] = {
        name = "Homepie", 
        x1 = 8700, 
        y1 = 7800, 
        x2 = 9299,
        y2 = 8399,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },
    ["Hartburg"] = {
        name = "Hartburg", 
        x1 = 6600, 
        y1 = 11100, 
        x2 = 6897,
        y2 = 11696,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },  
    ["Overlook Hotel"] = {
        name = "Overlook Hotel", 
        x1 = 4500, 
        y1 = 6300, 
        x2 = 4799,
        y2 = 6599,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },  
    ["Monmouth County"] = {
        name = "Monmouth County", 
        x1 = 11700, 
        y1 = 7800, 
        x2 = 12899,
        y2 = 8999,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },  
    ["International Airport"] = {
        name = "International Airport", 
        x1 = 12865, 
        y1 = 4200, 
        x2 = 13447,
        y2 = 4796,
        isPvP = true,
        isPvE = false,
        isLock = false,
        isBlocked = false,
    },  
}

