
ParadiseZ = ParadiseZ or {}
-----------------------            ---------------------------
-- print(ParadiseZ.ZoneData["Louisville"].isBlocked)
ParadiseZ.ZoneDataBackup = {
    ["Bedford Falls"] = {
        name = "Bedford Falls",
        x1 = 12601,
        y1 = 9586,
        x2 = 14399,
        y2 = 11708,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Brandonberg"] = {
        name = "Brandonberg",
        x1 = 1951,
        y1 = 5703,
        x2 = 2871,
        y2 = 6450,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Celadon's Shag Pad"] = {
        name = "Celadon's Shag Pad",
        x1 = 5699,
        y1 = 5712,
        x2 = 5728,
        y2 = 5741,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Fallas Lake"] = {
        name = "Fallas Lake",
        x1 = 7043,
        y1 = 8162,
        x2 = 7546,
        y2 = 8572,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Fort Redstone"] = {
        name = "Fort Redstone",
        x1 = 5401,
        y1 = 11697,
        x2 = 5929,
        y2 = 12300,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Greenport"] = {
        name = "Greenport",
        x1 = 8017,
        y1 = 7407,
        x2 = 8700,
        y2 = 7800,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Hartburg"] = {
        name = "Hartburg",
        x1 = 6595,
        y1 = 11100,
        x2 = 6906,
        y2 = 11699,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Homepie"] = {
        name = "Homepie",
        x1 = 8680,
        y1 = 7797,
        x2 = 9315,
        y2 = 8399,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["International Airport"] = {
        name = "International Airport",
        x1 = 12856,
        y1 = 4197,
        x2 = 13500,
        y2 = 4800,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Jamieton"] = {
        name = "Jamieton",
        x1 = 5138,
        y1 = 9345,
        x2 = 6015,
        y2 = 10582,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Jayne's Town"] = {
        name = "Jayne's Town",
        x1 = 13000,
        y1 = 7180,
        x2 = 13273,
        y2 = 7581,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["LV Checkpoint"] = {
        name = "LV Checkpoint",
        x1 = 12404,
        y1 = 3905,
        x2 = 12568,
        y2 = 4365,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Lake Ivy Township"] = {
        name = "Lake Ivy Township",
        x1 = 8700,
        y1 = 9597,
        x2 = 9599,
        y2 = 10499,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Louisville"] = {
        name = "Louisville",
        x1 = 11959,
        y1 = 901,
        x2 = 14999,
        y2 = 4193,
        isKos = true,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["MarchRidge"] = {
        name = "MarchRidge",
        x1 = 9761,
        y1 = 12567,
        x2 = 10523,
        y2 = 13212,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Minutemen HQ"] = {
        name = "Minutemen HQ",
        x1 = 5681,
        y1 = 5726,
        x2 = 5698,
        y2 = 5739,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Monmouth County"] = {
        name = "Monmouth County",
        x1 = 11426,
        y1 = 7837,
        x2 = 12975,
        y2 = 8999,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Monmouth County Power Station"] = {
        name = "Monmouth County Power Station",
        x1 = 11809,
        y1 = 7876,
        x2 = 11870,
        y2 = 7943,
        isKos = SandboxVars.ParadiseZ.RadZoneisKos or false,
        isPvE = SandboxVars.ParadiseZ.RadZoneisPvE or false,
        isSafe = SandboxVars.ParadiseZ.RadZoneisSafe or false,
        isBlocked = SandboxVars.ParadiseZ.RadZoneisBlocked or false,
        isRad = true,
    },
    ["Muldraugh"] = {
        name = "Muldraugh",
        x1 = 10559,
        y1 = 9137,
        x2 = 11100,
        y2 = 10748,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Over The River"] = {
        name = "Over The River",
        x1 = 11100,
        y1 = 3900,
        x2 = 12279,
        y2 = 6336,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Raven Creek"] = {
        name = "Raven Creek",
        x1 = 2356,
        y1 = 11045,
        x2 = 5105,
        y2 = 13801,
        isKos = true,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Research Facility"] = {
        name = "Research Facility",
        x1 = 5478,
        y1 = 12388,
        x2 = 5969,
        y2 = 12821,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Riverside"] = {
        name = "Riverside",
        x1 = 5695,
        y1 = 5099,
        x2 = 6900,
        y2 = 5625,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Rosewood"] = {
        name = "Rosewood",
        x1 = 7504,
        y1 = 11222,
        x2 = 9403,
        y2 = 12598,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Rosewood Prison"] = {
        name = "Rosewood Prison",
        x1 = 7584,
        y1 = 11760,
        x2 = 7784,
        y2 = 11981,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Shipping Port"] = {
        name = "Shipping Port",
        x1 = 12251,
        y1 = 4498,
        x2 = 12905,
        y2 = 5104,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Slugger Stadium"] = {
        name = "Slugger Stadium",
        x1 = 12978,
        y1 = 1533,
        x2 = 13067,
        y2 = 1622,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["South LV"] = {
        name = "South LV",
        x1 = 13008,
        y1 = 4906,
        x2 = 14431,
        y2 = 5990,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["The Farm"] = {
        name = "The Farm",
        x1 = 8451,
        y1 = 8732,
        x2 = 8684,
        y2 = 8898,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["The Gauntlet"] = {
        name = "The Gauntlet",
        x1 = 8278,
        y1 = 5990,
        x2 = 8318,
        y2 = 6047,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["The Gucci Chateau"] = {
        name = "The Gucci Chateau",
        x1 = 12713,
        y1 = 5024,
        x2 = 12755,
        y2 = 5087,
        isKos = false,
        isPvE = true,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["Thunder Dome"] = {
        name = "Thunder Dome",
        x1 = 12986,
        y1 = 1540,
        x2 = 13017,
        y2 = 1571,
        isKos = true,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["West Maple Country Club"] = {
        name = "West Maple Country Club",
        x1 = 5490,
        y1 = 6378,
        x2 = 5823,
        y2 = 6683,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
    ["West Point"] = {
        name = "West Point",
        x1 = 9901,
        y1 = 6510,
        x2 = 12299,
        y2 = 7199,
        isKos = false,
        isPvE = false,
        isSafe = false,
        isBlocked = false,
        isRad = false,
    },
}
     
--ParadiseZ.ZoneData = ParadiseZ.ZoneData or ParadiseZ.ZoneDataBackup

function ParadiseZ.parseZone(strList)
    strList = strList or SandboxVars.ParadiseZ.BlockedList

    for k,v in pairs(ParadiseZ.ZoneData) do
        v.isBlocked = false
    end

    for str in string.gmatch(strList, "[^;]+") do
        str = str:match("^%s*(.-)%s*$")
        if ParadiseZ.ZoneData[str] then
            ParadiseZ.ZoneData[str].isBlocked = true
        end
    end
end



function ParadiseZ.init()
    ParadiseZ.parseZone()
end
Events.OnCreatePlayer.Remove(ParadiseZ.init)
--Events.OnCreatePlayer.Add(ParadiseZ.init)